# Generated by Django 5.0.7 on 2025-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_trigger_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
