# Generated by Django 5.1.6 on 2025-03-01 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_inventory_reorder_trigger_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProcess',
            new_name='ProcessedOrder',
        ),
        migrations.AlterField(
            model_name='customerorderitems',
            name='customer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_items', to='base.customerorder'),
        ),
        migrations.AlterField(
            model_name='processedlineitems',
            name='customer_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='processed_items', to='base.customerorderitems'),
        ),
        migrations.AlterField(
            model_name='processedorder',
            name='customer_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.customerorder'),
        ),
    ]
